//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManage.DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string ID_Users { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Date_of_Birth { get; set; }
        public string Type { get; set; }
        public string Notes { get; set; }
        public string PathImage { get; set; }
    }
}
