//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManage.DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public string ID_Borrow { get; set; }
        public string ID_Book { get; set; }
        public string ID_User { get; set; }
        public string ID_Employee { get; set; }
        public System.DateTime Borrow_Date { get; set; }
        public Nullable<System.DateTime> Pay_Day { get; set; }
        public string Notes { get; set; }
    }
}
